
/**
 * Class for exceptions generated by the router or controllers.
 */
export class RouteException {
  status: number;
  body: {[key: string]: string | number | boolean}[]

  constructor(status: number, body?: {[key: string]: string | number | boolean}[]) {
    this.status = status;
    this.body = body ?? [];
  }
}
