/**
 * Class for exceptions generated by the router or controllers.
 */
export class RouteException extends Error {
  status: number;
  body: {[key: string]: string | number | boolean}[];


  constructor(status: number, body?: {[key: string]: string | number | boolean}[]) {
    super();
    this.status = status;
    this.body = body ?? [];
  }
}
